// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

        apiKey: "AIzaSyCAB0kBnba9XsCtWDuqZRFagy6MGAr8awI",
        authDomain: "recoverybodystore.firebaseapp.com",
        databaseURL: "https://recoverybodystore-default-rtdb.asia-southeast1.firebasedatabase.app",
        projectId: "recoverybodystore",
        storageBucket: "recoverybodystore.appspot.com",
        messagingSenderId: "812183167869",
        appId: "1:812183167869:web:5ea2516c6fed43f9b82214",
        measurementId: "G-DXJFSX2V0Z"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhihhs4sQafVQFfXNW-ZNYL8OB5VrSrkc',
    appId: '1:768970769332:android:48e61993647ddd773068e1',
    messagingSenderId: '768970769332',
    projectId: 'empyrean-surge-395513',
    storageBucket: 'empyrean-surge-395513.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbXohR18yZYDkYmJk2nwOJGTK-j6SuQw',
    appId: '1:768970769332:ios:0196372aca467da03068e1',
    messagingSenderId: '768970769332',
    projectId: 'empyrean-surge-395513',
    storageBucket: 'empyrean-surge-395513.appspot.com',
    iosClientId: '768970769332-03g8jjqq6fmdlm10cq7no6abo3j1qbvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.trywithkokoExpense2',
  );
}
